"use client"
import { useEffect, useState } from "react"
import { ArrowRight, Check, Minus } from "lucide-react"
import { motion } from "framer-motion"

function ScramblePrice({ target, prefix = "$" }: { target: string; prefix?: string }) {
  const [display, setDisplay] = useState(target.replace(/[0-9]/g, "0"))
  useEffect(() => { let it = 0; const max = 14; const iv = setInterval(() => { if (it >= max) { setDisplay(target); clearInterval(iv); return }; setDisplay(target.split("").map((c, i) => { if (!/[0-9]/.test(c)) return c; if (it > max - 4 && i < it - (max - 4)) return c; return String(Math.floor(Math.random() * 10)) }).join("")); it++ }, 50); return () => clearInterval(iv) }, [target])
  return <span className="font-mono font-bold" style={{ fontVariantNumeric: "tabular-nums" }}>{prefix}{display}</span>
}

const TIERS = [
  { name: "DIAGNOSTICO", price: "0", period: "/ eval", tag: null, description: "Evaluacion inicial de preparacion EUDR. Hoja de ruta clara.", features: [{ text: "Cuestionario EUDR Readiness", included: true },{ text: "Revision de brechas", included: true },{ text: "Mapa de cadena", included: true },{ text: "Informe ejecutivo PDF", included: true },{ text: "Sesion 60 min", included: true },{ text: "Scoring automatizado", included: false }], cta: "SOLICITAR", highlighted: false },
  { name: "PILOTO", price: "499", period: "/ mes", tag: "RECOMENDADO", description: "1 cooperativa, hasta 50 productores. Scoring EUDR, DDS, copiloto.", features: [{ text: "Onboarding cooperativa", included: true },{ text: "Hasta 50 productores", included: true },{ text: "Geolocalizacion", included: true },{ text: "Scoring EUDR x lote", included: true },{ text: "DDS exportable PDF", included: true },{ text: "Copiloto EUDR", included: true },{ text: "Soporte 3 meses", included: true }], cta: "COMENZAR", highlighted: true },
  { name: "ENTERPRISE", price: "CUSTOM", period: "", tag: null, description: "Multi-cooperativa. Multi-pais. API/ERP. Blockchain.", features: [{ text: "Multi-cooperativa", included: true },{ text: "Integracion API/ERP", included: true },{ text: "Blockchain", included: true },{ text: "Validacion satelital", included: true },{ text: "Auditoria anual", included: true },{ text: "SLA 99.5%", included: true },{ text: "Gerente dedicado", included: true }], cta: "CONTACTAR", highlighted: false },
]

function PricingCard({ tier, index }: { tier: typeof TIERS[0]; index: number }) {
  const isCustom = tier.price === "CUSTOM"
  return (<motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.1 }} className={`flex flex-col h-full ${tier.highlighted ? "border-2 border-foreground bg-foreground text-background" : "border-2 border-foreground bg-background text-foreground"}`}>
    <div className={`flex items-center justify-between px-3 sm:px-5 py-2 sm:py-3 border-b-2 ${tier.highlighted ? "border-background/20" : "border-foreground"}`}><span className="text-[8px] sm:text-[10px] tracking-[0.15em] uppercase font-mono">{tier.name}</span><div className="flex items-center gap-1 sm:gap-2">{tier.tag && <span className="bg-[#ea580c] text-background text-[7px] sm:text-[9px] tracking-[0.15em] uppercase px-1.5 sm:px-2 py-0.5 font-mono">{tier.tag}</span>}<span className="text-[8px] sm:text-[10px] opacity-50 font-mono">{String(index + 1).padStart(2, "0")}</span></div></div>
    <div className="px-3 sm:px-5 pt-4 sm:pt-6 pb-3 sm:pb-4"><div className="flex items-baseline gap-1">{isCustom ? <span className="text-xl sm:text-3xl lg:text-4xl font-mono font-bold">CUSTOM</span> : <span className="text-xl sm:text-3xl lg:text-4xl"><ScramblePrice target={tier.price} /></span>}{tier.period && <span className={`text-[10px] sm:text-xs font-mono tracking-widest uppercase ${tier.highlighted ? "text-background/50" : "text-muted-foreground"}`}>{tier.period}</span>}</div><p className={`text-[10px] sm:text-xs font-mono mt-2 sm:mt-3 leading-relaxed ${tier.highlighted ? "text-background/60" : "text-muted-foreground"}`}>{tier.description}</p></div>
    <div className={`flex-1 px-3 sm:px-5 py-3 sm:py-4 border-t-2 ${tier.highlighted ? "border-background/20" : "border-foreground"}`}><div className="flex flex-col gap-2 sm:gap-3">{tier.features.map((f, fi) => (<div key={fi} className="flex items-start gap-2 sm:gap-3">{f.included ? <Check size={10} className="mt-0.5 shrink-0 text-[#ea580c]" /> : <Minus size={10} className="mt-0.5 shrink-0 text-muted-foreground/40" />}<span className={`text-[10px] sm:text-xs font-mono leading-relaxed ${f.included ? "" : "text-muted-foreground/40 line-through"}`}>{f.text}</span></div>))}</div></div>
    <div className="px-3 sm:px-5 pb-4 sm:pb-5 pt-2 sm:pt-3"><a href="mailto:sinapsisinnovadoraperu@gmail.com?subject=Plan%20Forest%20Trace%20AI" className={`group w-full flex items-center justify-center gap-0 text-[10px] sm:text-xs font-mono tracking-wider uppercase ${tier.highlighted ? "bg-background text-foreground" : "bg-foreground text-background"}`}><span className="flex items-center justify-center w-7 h-7 sm:w-9 sm:h-9 bg-[#ea580c]"><ArrowRight size={12} className="text-background sm:w-3.5 sm:h-3.5" /></span><span className="flex-1 py-2 sm:py-2.5">{tier.cta}</span></a></div>
  </motion.div>)
}

export function PricingSection() {
  return (<section className="w-full px-4 py-12 sm:px-6 sm:py-16 lg:px-12 lg:py-20"><div className="flex items-center gap-3 sm:gap-4 mb-6 sm:mb-8"><span className="text-[8px] sm:text-[10px] tracking-[0.2em] uppercase text-muted-foreground font-mono">{"// SECCION: PLANES_PRECIO"}</span><div className="flex-1 border-t border-border"/><span className="text-[8px] sm:text-[10px] tracking-[0.2em] uppercase text-muted-foreground font-mono">006</span></div><div className="flex flex-col gap-3 sm:gap-6 mb-8 sm:mb-12"><h2 className="text-lg sm:text-2xl lg:text-3xl font-mono font-bold tracking-tight uppercase text-balance">Selecciona tu nivel</h2><p className="text-[10px] sm:text-xs lg:text-sm font-mono text-muted-foreground leading-relaxed max-w-md">Todos los planes incluyen acceso a la plataforma Forest Trace AI con scoring automatizado y copiloto EUDR.</p></div><div className="grid grid-cols-1 md:grid-cols-3 gap-3 sm:gap-0">{TIERS.map((t, i) => (<PricingCard key={t.name} tier={t} index={i} />))}</div></section>)
}
