"use client"
import { useEffect, useRef } from "react"
import { useTheme } from "next-themes"
export function DitherCard() {
  const c = useRef<HTMLCanvasElement>(null)
  const { resolvedTheme } = useTheme()
  useEffect(() => { const cv = c.current; if (!cv) return; const ctx = cv.getContext("2d"); if (!ctx) return; const w = 320; const h = 240; cv.width = w; cv.height = h; const isDark = resolvedTheme === "dark"; const dv = isDark ? 230 : 10; const lv = isDark ? 15 : 230; const id = ctx.createImageData(w, h); const d = id.data; for (let y = 0; y < h; y++) { for (let x = 0; x < w; x++) { const idx = (y * w + x) * 4; const cx = w / 2; const cy = h / 2; const dist = Math.sqrt((x - cx) ** 2 + (y - cy) ** 2); const md = Math.sqrt(cx ** 2 + cy ** 2); const g = 1 - dist / md; const wave = Math.sin(x * 0.08) * Math.cos(y * 0.04) * 0.25; const bm = [[0, 2], [3, 1]]; const bv = bm[y % 2][x % 2] / 4; const val = g + wave; const dt = val > bv ? dv : lv; d[idx] = dt; d[idx + 1] = dt; d[idx + 2] = dt; d[idx + 3] = 255 } }; ctx.putImageData(id, 0, 0) }, [resolvedTheme])
  return (<div className="flex flex-col h-full"><div className="flex items-center justify-between border-b-2 border-foreground px-4 py-2"><span className="text-[10px] tracking-widest text-muted-foreground uppercase">geobosques.satelite</span><span className="text-[10px] tracking-widest text-muted-foreground">320x240</span></div><div className="flex-1 flex flex-col items-center justify-center p-4 bg-background gap-3"><canvas ref={c} className="w-full h-auto rounded-full max-w-[160px]" style={{ imageRendering: "pixelated" }} aria-label="Analisis satelital de parcela" /><span className="text-[10px] tracking-[0.15em] uppercase text-muted-foreground font-mono text-center">sin perdida de bosque post-2020</span><span className="text-[9px] tracking-[0.15em] uppercase text-[#ea580c] font-mono">GeoBosques · MINAM · SERFOR</span></div></div>)
}
