import type { Metadata, Viewport } from 'next'
import { JetBrains_Mono } from 'next/font/google'
import { GeistPixelGrid } from 'geist/font/pixel'
import { ThemeProvider } from '@/components/theme-provider'
import './globals.css'
const jetbrainsMono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-mono' })
export const metadata: Metadata = { title: 'Forest Trace AI — Cumplimiento EUDR Automatizado', description: 'Plataforma SaaS de trazabilidad, debida diligencia y evidencia agroexportadora para cumplimiento EUDR. Scoring de riesgo, 8 ambitos de legalidad, DDS exportable. Para cooperativas y exportadores peruanos de cafe y cacao.', keywords: ['EUDR','cumplimiento','cafe','cacao','trazabilidad','Peru','diligencia debida','DDS','geolocalizacion','SERFOR','MIDAGRI'], authors: [{ name: 'SINAPSIS INNOVADORA S.A.C.' }], robots: { index: true, follow: true }, openGraph: { type: 'website', locale: 'es_PE', title: 'Forest Trace AI — Cumplimiento EUDR Automatizado', description: 'Plataforma SaaS de trazabilidad y debida diligencia EUDR para agroexportadores peruanos.', siteName: 'Forest Trace AI' } }
export const viewport: Viewport = { themeColor: '#F2F1EA', width: 'device-width', initialScale: 1 }
export default function RootLayout({ children }: { children: React.ReactNode }) { return (<html lang="es" className={`${jetbrainsMono.variable} ${GeistPixelGrid.variable}`} suppressHydrationWarning><head><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Que es el EUDR y a quien aplica?","acceptedAnswer":{"@type":"Answer","text":"El Reglamento (UE) 2023/1115 exige que productos agroexportados a la UE esten libres de deforestacion, producidos legalmente y respaldados por una Declaracion de Debida Diligencia (DDS). Aplica a operadores (grandes desde dic 2025, PYMES desde 30 jun 2026)."}},{"@type":"Question","name":"Como ayuda el DS 020-2015-MINAGRI al cumplimiento EUDR?","acceptedAnswer":{"@type":"Answer","text":"El DS 020-2015 define los sistemas agroforestales en Peru como uso agrario. El OJ C/2025/4524 confirma que estos sistemas NO son bosque. Una parcela de cafe bajo sombra que siempre fue agroforestal no fue deforestada."}},{"@type":"Question","name":"Que entidades peruanas estan involucradas en el cumplimiento?","acceptedAnswer":{"@type":"Answer","text":"MIDAGRI (Padron de Productores), SERFOR (clasificacion de uso de suelo), SENASA (certificado fitosanitario), MINAM/GeoBosques (monitoreo satelital), SUNARP (titulos de propiedad), SUNAT (RUC/DUA) y PROMPERU (guias de cumplimiento)."}},{"@type":"Question","name":"Forest Trace AI garantiza el cumplimiento EUDR?","acceptedAnswer":{"@type":"Answer","text":"No. Es una herramienta de apoyo documental y trazabilidad. La responsabilidad del cumplimiento corresponde al operador economico y a sus asesores calificados."}}]})}}/></head><body className="font-mono antialiased"><ThemeProvider attribute="class" defaultTheme="light" enableSystem={false} disableTransitionOnChange>{children}</ThemeProvider></body></html>) }
